services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5001"
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "5002:5002"
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
